### ISSUE TITLE
Create an audio channel

### ISSUE THREAD

**Issue by cptarnie** [b6938236/high-quality-chat#1]
## Story / Task Details
- [x] Enable connection to a server via "connection string"
- [x] Create a one to one server for voice communication

## Acceptance Scenarios
\- Given: user is prompted for server connection string  
\- When: user pastes in connection string  
\- Then:  user is connected to server  

\- Given: user has connected to the server
\- When: user speaks into microphone
\- Then: server receives voice communication

## Done Done Criteria

Tests passed and merged into master

---

User story reference: Join an audio channel so that I can participate in the recording

**Comment by b6938236** [comment]
Connection string done, just a base64(username;password;server).  There are some things we may need to look into (string compression, password hash instead of password).  See b433b095fe746f392867cb75b4058d03d4c6d376

**Comment by b6938236** [comment]
One to one audio channel working (voice quality).  See f7520e236c17ea92d24138999718a4daf380fa05
