### ISSUE TITLE
Save full quality recordings

### ISSUE THREAD

**Issue by moconnell9** [b6938236/high-quality-chat#13]
## Story / Task Details
- [ ] Enable recording from a local source to disk
     - [X] studio quality
     - [ ] voice quality

## Acceptance Scenarios

Given: user joins session
When: user selects segment to save
Then: segment is saved to their disk without loss in quality

## Done Done Criteria

Tests passed and merged into master

----------------

User story reference: Be able to record from my own studio so I can use my own equipment and not have to travel

**Comment by b6938236** [comment]
Studio quality saves were done when creating the HQ recorder

**Comment by b6938236** [comment]
see 800385489212356b12f3d1caacd14aaf59366b8f
