### ISSUE TITLE
Create Thumbnail for Each Recording in a Session Menu/Toolbar

### ISSUE THREAD

**Issue by moconnell9** [b6938236/high-quality-chat#14]
## Story / Task Details

- [x] create menu/tab for viewing recent recordings
- [ ] enable playback of each recording
~- [ ] enable deletion of each recording~

## Acceptance Scenarios

Given: user joins session
When: user begins and ends a recording
Then: recording is automatically saved and displayed to all users in the toolbar

Given: user joins session
When: user selects a past recording and selects "playback"
Then: recording is played to all users

Given: user joins session
When: user selects a past recording and selects "delete"
Then: pop-up asks producer for permission to delete (if producer- still asks to confirm) and deletes or not accordingly

## Done Done Criteria

Tests passed and merged into master

----------------

User story reference: Be able to view thumbnails of recent recordings so I can easily discern my progress and status

**Comment by b6938236** [comment]
test for github slack integration

**Comment by b6938236** [comment]
This was never a feature we planned to implement
