### ISSUE TITLE
Choose which folder to save recordings

### ISSUE THREAD

**Issue by cptarnie** [b6938236/high-quality-chat#16]
## Story / Task Details
- [x] Option in settings for choosing recordings destination

## Acceptance Scenarios
\- Given: user is navigating the main menu
\- When: settings menu is accessed
\- Then: user has the option to choose destination folder

## Done Done Criteria

Tests passed and merged into master

---

User story reference: Choose which folder to save recordings

**Comment by faizanv** [comment]
Can currently be set by directly editing conn.conf
