### ISSUE TITLE
Get Clear and Immediate Feedback for certain aspects of the session UI

### ISSUE THREAD

**Issue by masterhuddy** [b6938236/high-quality-chat#17]
## Story / Task Details
- [x] Get notifications for when recordings are sent
- [x] Notify when someone in the session is actively recording

## Acceptance Scenarios

Given: user clicks a UI element
When: user selects a recording to send
Then: the progress of their request is shown in some manner for that user

Given: user joins a session
When: user scans the UI and locates a representation of the other members in the session
Then: the status of whether or not a member is recording is shown for any member of the session

## Done Done Criteria

Tests passed and merged into master

User story reference: Get immediate and very clear feedback that things are loading, my button clicks were received

**Comment by b6938236** [comment]
Includes GUI hookups for chat

**Comment by moconnell9** [comment]
for "progress of request," the idea was originally to change the button text to "Pending Approval," which should be trivial to implement when requesting is possible. (unless someone has an alternative, that's fine)

**Comment by moconnell9** [comment]
perhaps a notification can populate in chat for who is recording? e.g. "[User1] is recording." and then later "[User1] has stopped recording."

**Comment by b6938236** [comment]
I'm pretty sure that the original mockup included a section separate from chat that contained status indicators like recording statuses.  However, the newly-added recording bar present on the actual recorder's client could just be mirrored to all other clients

**Comment by b6938236** [comment]
Status is just sent to chat windows
