### ISSUE TITLE
Be able to tell if application is recording

### ISSUE THREAD

**Issue by masterhuddy** [b6938236/high-quality-chat#19]
## Story / Task Details
- [ ] Add an element to the UI to make it clear when a user in the session is actively recording

## Acceptance Scenarios

Given: user joins a session
When: user selects the option to record
Then: the status of whether the session is actively recording is shown

## Done Done Criteria
Tests passed and merged into master

User story reference: Be able to tell at a glance if the app is recording or not so I don't waste time fiddling to figure it out

**Comment by moconnell9** [comment]
currently the image changes from a 'record' symbol to a 'stop' symbol when recording, and back when recording is done. A blinking "light" can be added as well

**Comment by moconnell9** [comment]
A progress bar loops when recording and freezes when not recording.
