### ISSUE TITLE
Create an audio chat

### ISSUE THREAD

**Issue by cptarnie** [b6938236/high-quality-chat#2]
## Story / Task Details
- [x] Set up one-to-one voice channel
- [x] Add preferred mic to settings
- [x] Add preferred output to settings

## Acceptance Scenarios
\- Given: user has joined a server
\- When: user attempts to speak through their microphone  
\- Then:  producer hears user microphone input through output

\- Given: user opens the settings page
\- When: user sets a default mic
\- Then: dropdown appears listing all local recording devices  

\- Given: user opens the settings page
\- When: user sets a default speaker
\- Then: dropbdown appears listing all local audio output devices

## Done Done Criteria

Tests passed and merged into master

---

User story reference: Talk to the voice talent in close to real time so I can provide feedback

**Comment by b6938236** [comment]
Focus on the settings GUI page

**Comment by b6938236** [comment]
HQCPhone.get_playback_devices() and .get_recording_devices() returns an array of strings suitable for Core.capture_device and Core.playback_device
