### ISSUE TITLE
Seeing the Status of other people's mics

### ISSUE THREAD

**Issue by masterhuddy** [b6938236/high-quality-chat#20]
## Story / Task Details
- [ ] Add microphone icon to a representation of each member in the session
- [ ] Link up the status of the audio stream for each user to their corresponding icon

## Acceptance Scenarios

Given: user joins a session
When: user scans the UI and locates a representation of the other members in the session
Then: the status of whether or not a member has their mic. on is shown for any member of the session

## Done Done Criteria

Tests passed and merged into master

User story reference: Be able to know the status of other people's mics so I know what's going on

**Comment by b6938236** [comment]
Message is sent in chat on state change
