### ISSUE TITLE
Switch between talking to artist and recording

### ISSUE THREAD

**Issue by masterhuddy** [b6938236/high-quality-chat#21]
## Story / Task Details
- [x] Allow authorized users to start and stop recording without disrupting low-quality audio chat
- [X] Add a setting for the producer to choose who in the session may record

## Acceptance Scenarios

Given: user creates a session
When: user selects certain members of the session to be able to record
Then: only the selected users have the option to record in that session

Given: user joins a session
When: user toggles whether or not they are recording, and whether or not their mic. is muted
Then: if the mic. is on but the recording is off, allow the user to access the low quality audio stream

## Done Done Criteria

Tests passed and merged into master

User story reference: Effortlessly switch between talking to the caller(s)/artists and recording a particular feed, and pausing the recording to talk again

**Comment by b6938236** [comment]
Some changes that the client wants means this issue has changed somewhat.

Enable client side speaker mute (except for previously recorded playback) and mic mute.
Local HQ recording is being handled by another team, this muting and unmuting should be handled entirely by liblinphone/hqc.py

**Comment by b6938236** [comment]
This will probably be done through SIP channel direction.  Unfortunately there just hasn't been a cleaner way to do it for some reason.
