### ISSUE TITLE
Be able to start and stop local recordings

### ISSUE THREAD

**Issue by cptarnie** [b6938236/high-quality-chat#22]
## Story / Task Details
- [ ] Add recording icon to indicate the status of the local recording
- [ ] Allow artist to click recording icon and change the status of the local recording

## Acceptance Scenarios
\- Given: artist is in a recording session
\- When: artist is actively recording
\- Then: recording icon indicates a recording taking place

\- Given: artist is in a recording session
\- When: artist clicks the recording icon
\- Then: status of the local recording changes

## Done Done Criteria

Tests passed and merged into master

---

User story reference: Be able to start and stop local recording so I don't fill my hard drive

**Comment by moconnell9** [comment]
When artist clicks the recording icon: the icon changes to a 'stop' icon
When artist is actively recording: a progress bar loops (is frozen otherwise)
