### ISSUE TITLE
Listen to saved audio segments

### ISSUE THREAD

**Issue by cptarnie** [b6938236/high-quality-chat#23]
## Story / Task Details
- [x] Mute the incoming low quality stream
- [x] Playback the pre-recorded low quality stream

## Acceptance Scenarios
\- Given: artist wants to listen to a recording
\- When: artist selects a recording to listen to
\- Then: the low quality chat is muted

\- Given: artist wants to listen to a recording
\- When: artist selects a recording to listen to
\- Then: pre-recorded stream is played

## Done Done Criteria

Tests passed and merged into master

---

User story reference: Listen to audio segments the producer has marked out so I can see what has been recorded

**Comment by b6938236** [comment]
See previous comments on playback.  Everything works except for 0 volume
