### ISSUE TITLE
Listening to marked out Audio Segments

### ISSUE THREAD

**Issue by masterhuddy** [b6938236/high-quality-chat#24]
## Story / Task Details
- [ ] Allow users to mute the oncoming low quality audio stream
- [ ] Allow playback for observers of the low quality audio stream the producer has marked out

## Acceptance Scenarios

Given: user joins a session
When: user selects a UI element representing the muting of the audio stream
Then: the low quality audio stream is muted for that user

Given: user joins a session
When: user selects a section of the low quality audio stream marked out by the producer
Then: the selected audio will playback for the user

## Done Done Criteria

Tests passed and merged into master

User story reference: Listen to audio segments the producer has marked out so I can see what has been recorded

**Comment by moconnell9** [comment]
Users are able to mute the incoming audio stream with the mute functionality of their computers, and conversely mute themselves with the app's 'mute' icon.

'Marking out' is no longer a goal or a feature of our application; therefore this issue is no longer an issue.
