### ISSUE TITLE
Start an audio server

### ISSUE THREAD

**Issue by cptarnie** [b6938236/high-quality-chat#3]
## Story / Task Details
- [x] Create server connection GUI
~~- [ ] Create server setup GUI~~

## Acceptance Scenarios
~~\- Given: user starts application~~
~~\- When: user selects producer type~~
~~\- Then: user is shown server setup screen~~

\- Given: user starts application
\- When: user selects interested party or artist type
\- Then: user is shown server connection screen

## Done Done Criteria

Tests passed and merged into master

---

User story reference: Start an audio channel so I can chat with the voice talent

**Comment by b6938236** [comment]
This is the three category selection screen (artist, producer, interested party).  4 buttons, one for each of the three categories and one for settings.  The three major buttons should have onmouseover text to describe the functions as detailed in the prototype last semester.

**Comment by b6938236** [comment]
Due to changes in backend, a user selecting the 'producer role' no longer configures a server.  We may add some of this functionality in later, but as of now it is unnecessary.

This part of the GUI should replace conn.conf [ConnectionDetails]

**Comment by b6938236** [comment]
Issue closed with c0ebb505ac1757ae600ed388e803a24db23621f9 and 45ba5c901a5d1bd8ff623b42714881e7440b3789
