### ISSUE TITLE
Join chat server when you join the call

### ISSUE THREAD

**Issue by b6938236** [b6938236/high-quality-chat#33]
- [ ] When connecting to the SIP server, also connect to the chat server

Done:

Given: Chat server is running on the same IP address as the SIP server
When: The app registers on the SIP server
Then: The app registers on the chat server

Done done:

Tested, merge to master

**Comment by b6938236** [comment]
When you make the single HQCPhone object also make a HQCChat object.  The chat server is located on the same IP address as the SIP server, but on port 9000

**Comment by masterhuddy** [comment]
A single chat server is created from the details in the conn.conf file, upon entry in the session screen. A way to gracefully disconnect from that object still needs to be implemented.
