### ISSUE TITLE
Receive proof recordings

### ISSUE THREAD

**Issue by cptarnie** [b6938236/high-quality-chat#4]
## Story / Task Details
- [x] Save voice quality audio streams to disk
- [x] Cut voice quality audio streams into arbitrary chunks

## Acceptance Scenarios
\- Given: server has been created
\- When: voice communication is received
\- Then: voice quality audio is saved to disk

\- Given: voice communication is being received
\- When: producer hits a "mark out" button
\- Then: voice quality audio is cut into pieces

## Done Done Criteria

Tests passed and merged into master

---

User story reference: Receive, with minimal delay, proof recordings so I can use them

**Comment by b6938236** [comment]
Assuming you have some audio stream(s) or incoming file(s), save it to disk.  Assuming you have some list of timestamps, segment the audio before saving to disk.
