### ISSUE TITLE
Receive studio ready recordings

### ISSUE THREAD

**Issue by cptarnie** [b6938236/high-quality-chat#5]
## Story / Task Details
This is the GUI side
- [ ] Download studio ready recordings
- [ ] Send studio ready recordings
- [ ] Cut studio quality audio files into arbitrary chunks

## Acceptance Scenarios
\- Given: artist participates in an audio recording
\- When: artist leaves the channel
\- Then: server receives the studio ready recording from artist

\- Given: artist participates in an audio recording
\- When: artist leaves the channel
\- Then: artist sends the server studio ready recordings

\- Given: voice communication is being received
\- When: producer hits a "mark out" button
\- Then: studio quality audio is cut into pieces

## Done Done Criteria

Tests passed and merged into master

---

User story reference: Receive, with some delay, studio ready recordings so I can use them

**Comment by moconnell9** [comment]
Download/send are taken care of by the 'Request' button added. Necessarily, a scrolling list of clips was also added for selection, to be requested/downloaded.

A "crop out" button was added for audio cutting purposes.
