### ISSUE TITLE
Save audio for later use

### ISSUE THREAD

**Issue by cptarnie** [b6938236/high-quality-chat#6]
## Story / Task Details
- [x] Keep server up and listening for connections
- [x] Gracefully tear down server

## Acceptance Scenarios
\- Given: the server is started
\- When: nobody connects to the server
\- Then: keep the server up

\- Given: the server is started
\- When: the producer wants to end the session
\- Then: gracefully shut down the server

## Done Done Criteria

Tests passed and merged into master

---

User story reference: Be able to save my audio at any time so I can use them later

**Comment by b6938236** [comment]
Due to the use of an independent SIP group chat system, this is already done.
