### ISSUE TITLE
Add placeholder text when the server connection screen is using stored values

### ISSUE THREAD

**Issue by b6938236** [b6938236/high-quality-chat#65]
- [ ] Add grey-ed out placeholder text when using default values, instead of just a blank box

Done:

Given: The config file contains all necessary values
When: The user has selected their role
Then: A default placeholder (eg, 'default') is displayed in grey text

Done Done:

Tested, merged to master

Instead of just a blank box, have the default value in the box be "Default" or "Configuration Value" or whatever sounds right.

It should be some shade of gray text that is completely removed if the user tries to enter in a new value.  If the user changes their mind and erases all the text they entered, the default placeholder value should come back

**Comment by moconnell9** [comment]
When a user selects their role, grey placeholder text fills the box until clicked on, and again if the box is cleared.

The size and position of the artist connection string textbox was adjusted to fill the screen better and fit more text.
