### ISSUE TITLE
Get the playback button to playback the audio recording

### ISSUE THREAD

**Issue by masterhuddy** [b6938236/high-quality-chat#96]
In the session screen, when you record some audio and then pause it, the clip appears in the right hand side of the screen, along with a green arrow representing a play button. Clicking on that button should change its graphic to the Pause button graphic and start a playback of that audio, as well as mute the current low quality audio stream. Create a function to accomplish this and call that function upon the green button being pressed.

**Comment by b6938236** [comment]
Playback functions are called but unexpected bugs result in a zero volume playback
